version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: "short-database-test"
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - test.env
    networks:
      - test
    volumes:
      - database_posgres_test:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: "short-link-test"
    restart: on-failure
    ports:
      - "8081:8080"
    env_file:
      - test.env
    depends_on:
      - db
    networks:
      - test

  migrator:
    profiles: [ "migrator" ]
    restart: on-failure
    build: ./migrator
    container_name: "migrator-test"
    ports:
      - "6000:6000"
    env_file:
      - test.env
    depends_on:
      - db
    networks:
      - test

volumes:
  database_posgres_test:

networks:
  test:
    driver: bridge